# Generated by Django 5.2.3 on 2025-06-14 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('creator', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('peer_ip', models.GenericIPAddressField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
